schema {
  query: Input
}

scalar JSON
scalar Decimal

type Input {
  deliveryCustomization: DeliveryCustomization!
  cart: Cart!
}

type DeliveryCustomization {
  metafield(namespace: String!, key: String!): Metafield
}

type Metafield {
  jsonValue: JSON!
}

type Cart {
  cost: CartCost!
  deliveryGroups: [CartDeliveryGroup!]!
}

type CartCost {
  subtotalAmount: MoneyV2!
}

type CartDeliveryGroup {
  deliveryAddress: MailingAddress
  deliveryOptions: [DeliveryOption!]!
}

type MailingAddress {
  countryCode: String
  zip: String
}

type DeliveryOption {
  handle: String!
  title: String
  code: String
  cost: MoneyV2!
}

type MoneyV2 {
  amount: Decimal!
}

type CartDeliveryOptionsTransformRunResult {
  operations: [Operation!]!
}

type Operation {
  deliveryOptionHide: DeliveryOptionHideOperation
  deliveryOptionRename: DeliveryOptionRenameOperation
  deliveryOptionMove: DeliveryOptionMoveOperation
}

type DeliveryOptionHideOperation {
  deliveryOptionHandle: String!
}

type DeliveryOptionRenameOperation {
  deliveryOptionHandle: String!
  title: String!
}

type DeliveryOptionMoveOperation {
  deliveryOptionHandle: String!
  index: Int!
}
