// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"smartdelivery/apps/api-go/internal/model"
)

func newDeliveryRule(db *gorm.DB, opts ...gen.DOOption) deliveryRule {
	_deliveryRule := deliveryRule{}

	_deliveryRule.deliveryRuleDo.UseDB(db, opts...)
	_deliveryRule.deliveryRuleDo.UseModel(&model.DeliveryRule{})

	tableName := _deliveryRule.deliveryRuleDo.TableName()
	_deliveryRule.ALL = field.NewAsterisk(tableName)
	_deliveryRule.ID = field.NewUint(tableName, "id")
	_deliveryRule.ShopID = field.NewUint(tableName, "shop_id")
	_deliveryRule.Name = field.NewString(tableName, "name")
	_deliveryRule.Priority = field.NewInt(tableName, "priority")
	_deliveryRule.Status = field.NewString(tableName, "status")
	_deliveryRule.ConditionType = field.NewString(tableName, "condition_type")
	_deliveryRule.ConditionValue = field.NewString(tableName, "condition_value")
	_deliveryRule.ActionType = field.NewString(tableName, "action_type")
	_deliveryRule.ActionValue = field.NewString(tableName, "action_value")
	_deliveryRule.CreatedAt = field.NewTime(tableName, "created_at")
	_deliveryRule.UpdatedAt = field.NewTime(tableName, "updated_at")
	_deliveryRule.AuditLogs = deliveryRuleHasManyAuditLogs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AuditLogs", "model.AuditLog"),
		Shop: struct {
			field.RelationField
			DeliveryRules struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
				AuditLogs struct {
					field.RelationField
				}
			}
			AuditLogs struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AuditLogs.Shop", "model.Shop"),
			DeliveryRules: struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
				AuditLogs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("AuditLogs.Shop.DeliveryRules", "model.DeliveryRule"),
				Shop: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AuditLogs.Shop.DeliveryRules.Shop", "model.Shop"),
				},
				AuditLogs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("AuditLogs.Shop.DeliveryRules.AuditLogs", "model.AuditLog"),
				},
			},
			AuditLogs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AuditLogs.Shop.AuditLogs", "model.AuditLog"),
			},
		},
		DeliveryRule: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("AuditLogs.DeliveryRule", "model.DeliveryRule"),
		},
	}

	_deliveryRule.Shop = deliveryRuleBelongsToShop{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Shop", "model.Shop"),
	}

	_deliveryRule.fillFieldMap()

	return _deliveryRule
}

type deliveryRule struct {
	deliveryRuleDo deliveryRuleDo

	ALL            field.Asterisk
	ID             field.Uint
	ShopID         field.Uint
	Name           field.String
	Priority       field.Int
	Status         field.String
	ConditionType  field.String
	ConditionValue field.String
	ActionType     field.String
	ActionValue    field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	AuditLogs      deliveryRuleHasManyAuditLogs

	Shop deliveryRuleBelongsToShop

	fieldMap map[string]field.Expr
}

func (d deliveryRule) Table(newTableName string) *deliveryRule {
	d.deliveryRuleDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deliveryRule) As(alias string) *deliveryRule {
	d.deliveryRuleDo.DO = *(d.deliveryRuleDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deliveryRule) updateTableName(table string) *deliveryRule {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint(table, "id")
	d.ShopID = field.NewUint(table, "shop_id")
	d.Name = field.NewString(table, "name")
	d.Priority = field.NewInt(table, "priority")
	d.Status = field.NewString(table, "status")
	d.ConditionType = field.NewString(table, "condition_type")
	d.ConditionValue = field.NewString(table, "condition_value")
	d.ActionType = field.NewString(table, "action_type")
	d.ActionValue = field.NewString(table, "action_value")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deliveryRule) WithContext(ctx context.Context) IDeliveryRuleDo {
	return d.deliveryRuleDo.WithContext(ctx)
}

func (d deliveryRule) TableName() string { return d.deliveryRuleDo.TableName() }

func (d deliveryRule) Alias() string { return d.deliveryRuleDo.Alias() }

func (d deliveryRule) Columns(cols ...field.Expr) gen.Columns {
	return d.deliveryRuleDo.Columns(cols...)
}

func (d *deliveryRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deliveryRule) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 13)
	d.fieldMap["id"] = d.ID
	d.fieldMap["shop_id"] = d.ShopID
	d.fieldMap["name"] = d.Name
	d.fieldMap["priority"] = d.Priority
	d.fieldMap["status"] = d.Status
	d.fieldMap["condition_type"] = d.ConditionType
	d.fieldMap["condition_value"] = d.ConditionValue
	d.fieldMap["action_type"] = d.ActionType
	d.fieldMap["action_value"] = d.ActionValue
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt

}

func (d deliveryRule) clone(db *gorm.DB) deliveryRule {
	d.deliveryRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	d.AuditLogs.db = db.Session(&gorm.Session{Initialized: true})
	d.AuditLogs.db.Statement.ConnPool = db.Statement.ConnPool
	d.Shop.db = db.Session(&gorm.Session{Initialized: true})
	d.Shop.db.Statement.ConnPool = db.Statement.ConnPool
	return d
}

func (d deliveryRule) replaceDB(db *gorm.DB) deliveryRule {
	d.deliveryRuleDo.ReplaceDB(db)
	d.AuditLogs.db = db.Session(&gorm.Session{})
	d.Shop.db = db.Session(&gorm.Session{})
	return d
}

type deliveryRuleHasManyAuditLogs struct {
	db *gorm.DB

	field.RelationField

	Shop struct {
		field.RelationField
		DeliveryRules struct {
			field.RelationField
			Shop struct {
				field.RelationField
			}
			AuditLogs struct {
				field.RelationField
			}
		}
		AuditLogs struct {
			field.RelationField
		}
	}
	DeliveryRule struct {
		field.RelationField
	}
}

func (a deliveryRuleHasManyAuditLogs) Where(conds ...field.Expr) *deliveryRuleHasManyAuditLogs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deliveryRuleHasManyAuditLogs) WithContext(ctx context.Context) *deliveryRuleHasManyAuditLogs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deliveryRuleHasManyAuditLogs) Session(session *gorm.Session) *deliveryRuleHasManyAuditLogs {
	a.db = a.db.Session(session)
	return &a
}

func (a deliveryRuleHasManyAuditLogs) Model(m *model.DeliveryRule) *deliveryRuleHasManyAuditLogsTx {
	return &deliveryRuleHasManyAuditLogsTx{a.db.Model(m).Association(a.Name())}
}

func (a deliveryRuleHasManyAuditLogs) Unscoped() *deliveryRuleHasManyAuditLogs {
	a.db = a.db.Unscoped()
	return &a
}

type deliveryRuleHasManyAuditLogsTx struct{ tx *gorm.Association }

func (a deliveryRuleHasManyAuditLogsTx) Find() (result []*model.AuditLog, err error) {
	return result, a.tx.Find(&result)
}

func (a deliveryRuleHasManyAuditLogsTx) Append(values ...*model.AuditLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deliveryRuleHasManyAuditLogsTx) Replace(values ...*model.AuditLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deliveryRuleHasManyAuditLogsTx) Delete(values ...*model.AuditLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deliveryRuleHasManyAuditLogsTx) Clear() error {
	return a.tx.Clear()
}

func (a deliveryRuleHasManyAuditLogsTx) Count() int64 {
	return a.tx.Count()
}

func (a deliveryRuleHasManyAuditLogsTx) Unscoped() *deliveryRuleHasManyAuditLogsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type deliveryRuleBelongsToShop struct {
	db *gorm.DB

	field.RelationField
}

func (a deliveryRuleBelongsToShop) Where(conds ...field.Expr) *deliveryRuleBelongsToShop {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deliveryRuleBelongsToShop) WithContext(ctx context.Context) *deliveryRuleBelongsToShop {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deliveryRuleBelongsToShop) Session(session *gorm.Session) *deliveryRuleBelongsToShop {
	a.db = a.db.Session(session)
	return &a
}

func (a deliveryRuleBelongsToShop) Model(m *model.DeliveryRule) *deliveryRuleBelongsToShopTx {
	return &deliveryRuleBelongsToShopTx{a.db.Model(m).Association(a.Name())}
}

func (a deliveryRuleBelongsToShop) Unscoped() *deliveryRuleBelongsToShop {
	a.db = a.db.Unscoped()
	return &a
}

type deliveryRuleBelongsToShopTx struct{ tx *gorm.Association }

func (a deliveryRuleBelongsToShopTx) Find() (result *model.Shop, err error) {
	return result, a.tx.Find(&result)
}

func (a deliveryRuleBelongsToShopTx) Append(values ...*model.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deliveryRuleBelongsToShopTx) Replace(values ...*model.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deliveryRuleBelongsToShopTx) Delete(values ...*model.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deliveryRuleBelongsToShopTx) Clear() error {
	return a.tx.Clear()
}

func (a deliveryRuleBelongsToShopTx) Count() int64 {
	return a.tx.Count()
}

func (a deliveryRuleBelongsToShopTx) Unscoped() *deliveryRuleBelongsToShopTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type deliveryRuleDo struct{ gen.DO }

type IDeliveryRuleDo interface {
	gen.SubQuery
	Debug() IDeliveryRuleDo
	WithContext(ctx context.Context) IDeliveryRuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeliveryRuleDo
	WriteDB() IDeliveryRuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeliveryRuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeliveryRuleDo
	Not(conds ...gen.Condition) IDeliveryRuleDo
	Or(conds ...gen.Condition) IDeliveryRuleDo
	Select(conds ...field.Expr) IDeliveryRuleDo
	Where(conds ...gen.Condition) IDeliveryRuleDo
	Order(conds ...field.Expr) IDeliveryRuleDo
	Distinct(cols ...field.Expr) IDeliveryRuleDo
	Omit(cols ...field.Expr) IDeliveryRuleDo
	Join(table schema.Tabler, on ...field.Expr) IDeliveryRuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeliveryRuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeliveryRuleDo
	Group(cols ...field.Expr) IDeliveryRuleDo
	Having(conds ...gen.Condition) IDeliveryRuleDo
	Limit(limit int) IDeliveryRuleDo
	Offset(offset int) IDeliveryRuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeliveryRuleDo
	Unscoped() IDeliveryRuleDo
	Create(values ...*model.DeliveryRule) error
	CreateInBatches(values []*model.DeliveryRule, batchSize int) error
	Save(values ...*model.DeliveryRule) error
	First() (*model.DeliveryRule, error)
	Take() (*model.DeliveryRule, error)
	Last() (*model.DeliveryRule, error)
	Find() ([]*model.DeliveryRule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeliveryRule, err error)
	FindInBatches(result *[]*model.DeliveryRule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeliveryRule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeliveryRuleDo
	Assign(attrs ...field.AssignExpr) IDeliveryRuleDo
	Joins(fields ...field.RelationField) IDeliveryRuleDo
	Preload(fields ...field.RelationField) IDeliveryRuleDo
	FirstOrInit() (*model.DeliveryRule, error)
	FirstOrCreate() (*model.DeliveryRule, error)
	FindByPage(offset int, limit int) (result []*model.DeliveryRule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeliveryRuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deliveryRuleDo) Debug() IDeliveryRuleDo {
	return d.withDO(d.DO.Debug())
}

func (d deliveryRuleDo) WithContext(ctx context.Context) IDeliveryRuleDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deliveryRuleDo) ReadDB() IDeliveryRuleDo {
	return d.Clauses(dbresolver.Read)
}

func (d deliveryRuleDo) WriteDB() IDeliveryRuleDo {
	return d.Clauses(dbresolver.Write)
}

func (d deliveryRuleDo) Session(config *gorm.Session) IDeliveryRuleDo {
	return d.withDO(d.DO.Session(config))
}

func (d deliveryRuleDo) Clauses(conds ...clause.Expression) IDeliveryRuleDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deliveryRuleDo) Returning(value interface{}, columns ...string) IDeliveryRuleDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deliveryRuleDo) Not(conds ...gen.Condition) IDeliveryRuleDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deliveryRuleDo) Or(conds ...gen.Condition) IDeliveryRuleDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deliveryRuleDo) Select(conds ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deliveryRuleDo) Where(conds ...gen.Condition) IDeliveryRuleDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deliveryRuleDo) Order(conds ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deliveryRuleDo) Distinct(cols ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deliveryRuleDo) Omit(cols ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deliveryRuleDo) Join(table schema.Tabler, on ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deliveryRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deliveryRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deliveryRuleDo) Group(cols ...field.Expr) IDeliveryRuleDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deliveryRuleDo) Having(conds ...gen.Condition) IDeliveryRuleDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deliveryRuleDo) Limit(limit int) IDeliveryRuleDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deliveryRuleDo) Offset(offset int) IDeliveryRuleDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deliveryRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeliveryRuleDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deliveryRuleDo) Unscoped() IDeliveryRuleDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deliveryRuleDo) Create(values ...*model.DeliveryRule) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deliveryRuleDo) CreateInBatches(values []*model.DeliveryRule, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deliveryRuleDo) Save(values ...*model.DeliveryRule) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deliveryRuleDo) First() (*model.DeliveryRule, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeliveryRule), nil
	}
}

func (d deliveryRuleDo) Take() (*model.DeliveryRule, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeliveryRule), nil
	}
}

func (d deliveryRuleDo) Last() (*model.DeliveryRule, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeliveryRule), nil
	}
}

func (d deliveryRuleDo) Find() ([]*model.DeliveryRule, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeliveryRule), err
}

func (d deliveryRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeliveryRule, err error) {
	buf := make([]*model.DeliveryRule, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deliveryRuleDo) FindInBatches(result *[]*model.DeliveryRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deliveryRuleDo) Attrs(attrs ...field.AssignExpr) IDeliveryRuleDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deliveryRuleDo) Assign(attrs ...field.AssignExpr) IDeliveryRuleDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deliveryRuleDo) Joins(fields ...field.RelationField) IDeliveryRuleDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deliveryRuleDo) Preload(fields ...field.RelationField) IDeliveryRuleDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deliveryRuleDo) FirstOrInit() (*model.DeliveryRule, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeliveryRule), nil
	}
}

func (d deliveryRuleDo) FirstOrCreate() (*model.DeliveryRule, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeliveryRule), nil
	}
}

func (d deliveryRuleDo) FindByPage(offset int, limit int) (result []*model.DeliveryRule, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deliveryRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deliveryRuleDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deliveryRuleDo) Delete(models ...*model.DeliveryRule) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deliveryRuleDo) withDO(do gen.Dao) *deliveryRuleDo {
	d.DO = *do.(*gen.DO)
	return d
}
