// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"smartdelivery/apps/api-go/internal/model"
)

func newFunctionConfigSnapshot(db *gorm.DB, opts ...gen.DOOption) functionConfigSnapshot {
	_functionConfigSnapshot := functionConfigSnapshot{}

	_functionConfigSnapshot.functionConfigSnapshotDo.UseDB(db, opts...)
	_functionConfigSnapshot.functionConfigSnapshotDo.UseModel(&model.FunctionConfigSnapshot{})

	tableName := _functionConfigSnapshot.functionConfigSnapshotDo.TableName()
	_functionConfigSnapshot.ALL = field.NewAsterisk(tableName)
	_functionConfigSnapshot.ID = field.NewUint(tableName, "id")
	_functionConfigSnapshot.ShopID = field.NewUint(tableName, "shop_id")
	_functionConfigSnapshot.ConfigJSON = field.NewString(tableName, "config_json")
	_functionConfigSnapshot.CreatedAt = field.NewTime(tableName, "created_at")
	_functionConfigSnapshot.Shop = functionConfigSnapshotBelongsToShop{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Shop", "model.Shop"),
		DeliveryRules: struct {
			field.RelationField
			Shop struct {
				field.RelationField
			}
			AuditLogs struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
				DeliveryRule struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Shop.DeliveryRules", "model.DeliveryRule"),
			Shop: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Shop.DeliveryRules.Shop", "model.Shop"),
			},
			AuditLogs: struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
				DeliveryRule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Shop.DeliveryRules.AuditLogs", "model.AuditLog"),
				Shop: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Shop.DeliveryRules.AuditLogs.Shop", "model.Shop"),
				},
				DeliveryRule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Shop.DeliveryRules.AuditLogs.DeliveryRule", "model.DeliveryRule"),
				},
			},
		},
		AuditLogs: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Shop.AuditLogs", "model.AuditLog"),
		},
		ConfigSnapshots: struct {
			field.RelationField
			Shop struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Shop.ConfigSnapshots", "model.FunctionConfigSnapshot"),
			Shop: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Shop.ConfigSnapshots.Shop", "model.Shop"),
			},
		},
	}

	_functionConfigSnapshot.fillFieldMap()

	return _functionConfigSnapshot
}

type functionConfigSnapshot struct {
	functionConfigSnapshotDo functionConfigSnapshotDo

	ALL        field.Asterisk
	ID         field.Uint
	ShopID     field.Uint
	ConfigJSON field.String
	CreatedAt  field.Time
	Shop       functionConfigSnapshotBelongsToShop

	fieldMap map[string]field.Expr
}

func (f functionConfigSnapshot) Table(newTableName string) *functionConfigSnapshot {
	f.functionConfigSnapshotDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f functionConfigSnapshot) As(alias string) *functionConfigSnapshot {
	f.functionConfigSnapshotDo.DO = *(f.functionConfigSnapshotDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *functionConfigSnapshot) updateTableName(table string) *functionConfigSnapshot {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewUint(table, "id")
	f.ShopID = field.NewUint(table, "shop_id")
	f.ConfigJSON = field.NewString(table, "config_json")
	f.CreatedAt = field.NewTime(table, "created_at")

	f.fillFieldMap()

	return f
}

func (f *functionConfigSnapshot) WithContext(ctx context.Context) IFunctionConfigSnapshotDo {
	return f.functionConfigSnapshotDo.WithContext(ctx)
}

func (f functionConfigSnapshot) TableName() string { return f.functionConfigSnapshotDo.TableName() }

func (f functionConfigSnapshot) Alias() string { return f.functionConfigSnapshotDo.Alias() }

func (f functionConfigSnapshot) Columns(cols ...field.Expr) gen.Columns {
	return f.functionConfigSnapshotDo.Columns(cols...)
}

func (f *functionConfigSnapshot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *functionConfigSnapshot) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 5)
	f.fieldMap["id"] = f.ID
	f.fieldMap["shop_id"] = f.ShopID
	f.fieldMap["config_json"] = f.ConfigJSON
	f.fieldMap["created_at"] = f.CreatedAt

}

func (f functionConfigSnapshot) clone(db *gorm.DB) functionConfigSnapshot {
	f.functionConfigSnapshotDo.ReplaceConnPool(db.Statement.ConnPool)
	f.Shop.db = db.Session(&gorm.Session{Initialized: true})
	f.Shop.db.Statement.ConnPool = db.Statement.ConnPool
	return f
}

func (f functionConfigSnapshot) replaceDB(db *gorm.DB) functionConfigSnapshot {
	f.functionConfigSnapshotDo.ReplaceDB(db)
	f.Shop.db = db.Session(&gorm.Session{})
	return f
}

type functionConfigSnapshotBelongsToShop struct {
	db *gorm.DB

	field.RelationField

	DeliveryRules struct {
		field.RelationField
		Shop struct {
			field.RelationField
		}
		AuditLogs struct {
			field.RelationField
			Shop struct {
				field.RelationField
			}
			DeliveryRule struct {
				field.RelationField
			}
		}
	}
	AuditLogs struct {
		field.RelationField
	}
	ConfigSnapshots struct {
		field.RelationField
		Shop struct {
			field.RelationField
		}
	}
}

func (a functionConfigSnapshotBelongsToShop) Where(conds ...field.Expr) *functionConfigSnapshotBelongsToShop {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a functionConfigSnapshotBelongsToShop) WithContext(ctx context.Context) *functionConfigSnapshotBelongsToShop {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a functionConfigSnapshotBelongsToShop) Session(session *gorm.Session) *functionConfigSnapshotBelongsToShop {
	a.db = a.db.Session(session)
	return &a
}

func (a functionConfigSnapshotBelongsToShop) Model(m *model.FunctionConfigSnapshot) *functionConfigSnapshotBelongsToShopTx {
	return &functionConfigSnapshotBelongsToShopTx{a.db.Model(m).Association(a.Name())}
}

func (a functionConfigSnapshotBelongsToShop) Unscoped() *functionConfigSnapshotBelongsToShop {
	a.db = a.db.Unscoped()
	return &a
}

type functionConfigSnapshotBelongsToShopTx struct{ tx *gorm.Association }

func (a functionConfigSnapshotBelongsToShopTx) Find() (result *model.Shop, err error) {
	return result, a.tx.Find(&result)
}

func (a functionConfigSnapshotBelongsToShopTx) Append(values ...*model.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a functionConfigSnapshotBelongsToShopTx) Replace(values ...*model.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a functionConfigSnapshotBelongsToShopTx) Delete(values ...*model.Shop) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a functionConfigSnapshotBelongsToShopTx) Clear() error {
	return a.tx.Clear()
}

func (a functionConfigSnapshotBelongsToShopTx) Count() int64 {
	return a.tx.Count()
}

func (a functionConfigSnapshotBelongsToShopTx) Unscoped() *functionConfigSnapshotBelongsToShopTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type functionConfigSnapshotDo struct{ gen.DO }

type IFunctionConfigSnapshotDo interface {
	gen.SubQuery
	Debug() IFunctionConfigSnapshotDo
	WithContext(ctx context.Context) IFunctionConfigSnapshotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFunctionConfigSnapshotDo
	WriteDB() IFunctionConfigSnapshotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFunctionConfigSnapshotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFunctionConfigSnapshotDo
	Not(conds ...gen.Condition) IFunctionConfigSnapshotDo
	Or(conds ...gen.Condition) IFunctionConfigSnapshotDo
	Select(conds ...field.Expr) IFunctionConfigSnapshotDo
	Where(conds ...gen.Condition) IFunctionConfigSnapshotDo
	Order(conds ...field.Expr) IFunctionConfigSnapshotDo
	Distinct(cols ...field.Expr) IFunctionConfigSnapshotDo
	Omit(cols ...field.Expr) IFunctionConfigSnapshotDo
	Join(table schema.Tabler, on ...field.Expr) IFunctionConfigSnapshotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFunctionConfigSnapshotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFunctionConfigSnapshotDo
	Group(cols ...field.Expr) IFunctionConfigSnapshotDo
	Having(conds ...gen.Condition) IFunctionConfigSnapshotDo
	Limit(limit int) IFunctionConfigSnapshotDo
	Offset(offset int) IFunctionConfigSnapshotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFunctionConfigSnapshotDo
	Unscoped() IFunctionConfigSnapshotDo
	Create(values ...*model.FunctionConfigSnapshot) error
	CreateInBatches(values []*model.FunctionConfigSnapshot, batchSize int) error
	Save(values ...*model.FunctionConfigSnapshot) error
	First() (*model.FunctionConfigSnapshot, error)
	Take() (*model.FunctionConfigSnapshot, error)
	Last() (*model.FunctionConfigSnapshot, error)
	Find() ([]*model.FunctionConfigSnapshot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FunctionConfigSnapshot, err error)
	FindInBatches(result *[]*model.FunctionConfigSnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FunctionConfigSnapshot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFunctionConfigSnapshotDo
	Assign(attrs ...field.AssignExpr) IFunctionConfigSnapshotDo
	Joins(fields ...field.RelationField) IFunctionConfigSnapshotDo
	Preload(fields ...field.RelationField) IFunctionConfigSnapshotDo
	FirstOrInit() (*model.FunctionConfigSnapshot, error)
	FirstOrCreate() (*model.FunctionConfigSnapshot, error)
	FindByPage(offset int, limit int) (result []*model.FunctionConfigSnapshot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFunctionConfigSnapshotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f functionConfigSnapshotDo) Debug() IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Debug())
}

func (f functionConfigSnapshotDo) WithContext(ctx context.Context) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f functionConfigSnapshotDo) ReadDB() IFunctionConfigSnapshotDo {
	return f.Clauses(dbresolver.Read)
}

func (f functionConfigSnapshotDo) WriteDB() IFunctionConfigSnapshotDo {
	return f.Clauses(dbresolver.Write)
}

func (f functionConfigSnapshotDo) Session(config *gorm.Session) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Session(config))
}

func (f functionConfigSnapshotDo) Clauses(conds ...clause.Expression) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f functionConfigSnapshotDo) Returning(value interface{}, columns ...string) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f functionConfigSnapshotDo) Not(conds ...gen.Condition) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f functionConfigSnapshotDo) Or(conds ...gen.Condition) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f functionConfigSnapshotDo) Select(conds ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f functionConfigSnapshotDo) Where(conds ...gen.Condition) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f functionConfigSnapshotDo) Order(conds ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f functionConfigSnapshotDo) Distinct(cols ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f functionConfigSnapshotDo) Omit(cols ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f functionConfigSnapshotDo) Join(table schema.Tabler, on ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f functionConfigSnapshotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f functionConfigSnapshotDo) RightJoin(table schema.Tabler, on ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f functionConfigSnapshotDo) Group(cols ...field.Expr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f functionConfigSnapshotDo) Having(conds ...gen.Condition) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f functionConfigSnapshotDo) Limit(limit int) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f functionConfigSnapshotDo) Offset(offset int) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f functionConfigSnapshotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f functionConfigSnapshotDo) Unscoped() IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Unscoped())
}

func (f functionConfigSnapshotDo) Create(values ...*model.FunctionConfigSnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f functionConfigSnapshotDo) CreateInBatches(values []*model.FunctionConfigSnapshot, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f functionConfigSnapshotDo) Save(values ...*model.FunctionConfigSnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f functionConfigSnapshotDo) First() (*model.FunctionConfigSnapshot, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FunctionConfigSnapshot), nil
	}
}

func (f functionConfigSnapshotDo) Take() (*model.FunctionConfigSnapshot, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FunctionConfigSnapshot), nil
	}
}

func (f functionConfigSnapshotDo) Last() (*model.FunctionConfigSnapshot, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FunctionConfigSnapshot), nil
	}
}

func (f functionConfigSnapshotDo) Find() ([]*model.FunctionConfigSnapshot, error) {
	result, err := f.DO.Find()
	return result.([]*model.FunctionConfigSnapshot), err
}

func (f functionConfigSnapshotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FunctionConfigSnapshot, err error) {
	buf := make([]*model.FunctionConfigSnapshot, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f functionConfigSnapshotDo) FindInBatches(result *[]*model.FunctionConfigSnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f functionConfigSnapshotDo) Attrs(attrs ...field.AssignExpr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f functionConfigSnapshotDo) Assign(attrs ...field.AssignExpr) IFunctionConfigSnapshotDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f functionConfigSnapshotDo) Joins(fields ...field.RelationField) IFunctionConfigSnapshotDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f functionConfigSnapshotDo) Preload(fields ...field.RelationField) IFunctionConfigSnapshotDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f functionConfigSnapshotDo) FirstOrInit() (*model.FunctionConfigSnapshot, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FunctionConfigSnapshot), nil
	}
}

func (f functionConfigSnapshotDo) FirstOrCreate() (*model.FunctionConfigSnapshot, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FunctionConfigSnapshot), nil
	}
}

func (f functionConfigSnapshotDo) FindByPage(offset int, limit int) (result []*model.FunctionConfigSnapshot, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f functionConfigSnapshotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f functionConfigSnapshotDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f functionConfigSnapshotDo) Delete(models ...*model.FunctionConfigSnapshot) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *functionConfigSnapshotDo) withDO(do gen.Dao) *functionConfigSnapshotDo {
	f.DO = *do.(*gen.DO)
	return f
}
