// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	AuditLog               *auditLog
	DeliveryRule           *deliveryRule
	FunctionConfigSnapshot *functionConfigSnapshot
	Shop                   *shop
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AuditLog = &Q.AuditLog
	DeliveryRule = &Q.DeliveryRule
	FunctionConfigSnapshot = &Q.FunctionConfigSnapshot
	Shop = &Q.Shop
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		AuditLog:               newAuditLog(db, opts...),
		DeliveryRule:           newDeliveryRule(db, opts...),
		FunctionConfigSnapshot: newFunctionConfigSnapshot(db, opts...),
		Shop:                   newShop(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AuditLog               auditLog
	DeliveryRule           deliveryRule
	FunctionConfigSnapshot functionConfigSnapshot
	Shop                   shop
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		AuditLog:               q.AuditLog.clone(db),
		DeliveryRule:           q.DeliveryRule.clone(db),
		FunctionConfigSnapshot: q.FunctionConfigSnapshot.clone(db),
		Shop:                   q.Shop.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		AuditLog:               q.AuditLog.replaceDB(db),
		DeliveryRule:           q.DeliveryRule.replaceDB(db),
		FunctionConfigSnapshot: q.FunctionConfigSnapshot.replaceDB(db),
		Shop:                   q.Shop.replaceDB(db),
	}
}

type queryCtx struct {
	AuditLog               IAuditLogDo
	DeliveryRule           IDeliveryRuleDo
	FunctionConfigSnapshot IFunctionConfigSnapshotDo
	Shop                   IShopDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AuditLog:               q.AuditLog.WithContext(ctx),
		DeliveryRule:           q.DeliveryRule.WithContext(ctx),
		FunctionConfigSnapshot: q.FunctionConfigSnapshot.WithContext(ctx),
		Shop:                   q.Shop.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
