// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"smartdelivery/apps/api-go/internal/model"
)

func newShop(db *gorm.DB, opts ...gen.DOOption) shop {
	_shop := shop{}

	_shop.shopDo.UseDB(db, opts...)
	_shop.shopDo.UseModel(&model.Shop{})

	tableName := _shop.shopDo.TableName()
	_shop.ALL = field.NewAsterisk(tableName)
	_shop.ID = field.NewUint(tableName, "id")
	_shop.Domain = field.NewString(tableName, "domain")
	_shop.CreatedAt = field.NewTime(tableName, "created_at")
	_shop.UpdatedAt = field.NewTime(tableName, "updated_at")
	_shop.DeliveryRules = shopHasManyDeliveryRules{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("DeliveryRules", "model.DeliveryRule"),
		Shop: struct {
			field.RelationField
			DeliveryRules struct {
				field.RelationField
			}
			AuditLogs struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
				DeliveryRule struct {
					field.RelationField
				}
			}
			ConfigSnapshots struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("DeliveryRules.Shop", "model.Shop"),
			DeliveryRules: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("DeliveryRules.Shop.DeliveryRules", "model.DeliveryRule"),
			},
			AuditLogs: struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
				DeliveryRule struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("DeliveryRules.Shop.AuditLogs", "model.AuditLog"),
				Shop: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("DeliveryRules.Shop.AuditLogs.Shop", "model.Shop"),
				},
				DeliveryRule: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("DeliveryRules.Shop.AuditLogs.DeliveryRule", "model.DeliveryRule"),
				},
			},
			ConfigSnapshots: struct {
				field.RelationField
				Shop struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("DeliveryRules.Shop.ConfigSnapshots", "model.FunctionConfigSnapshot"),
				Shop: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("DeliveryRules.Shop.ConfigSnapshots.Shop", "model.Shop"),
				},
			},
		},
		AuditLogs: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("DeliveryRules.AuditLogs", "model.AuditLog"),
		},
	}

	_shop.AuditLogs = shopHasManyAuditLogs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AuditLogs", "model.AuditLog"),
	}

	_shop.ConfigSnapshots = shopHasManyConfigSnapshots{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ConfigSnapshots", "model.FunctionConfigSnapshot"),
	}

	_shop.fillFieldMap()

	return _shop
}

type shop struct {
	shopDo shopDo

	ALL           field.Asterisk
	ID            field.Uint
	Domain        field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeliveryRules shopHasManyDeliveryRules

	AuditLogs shopHasManyAuditLogs

	ConfigSnapshots shopHasManyConfigSnapshots

	fieldMap map[string]field.Expr
}

func (s shop) Table(newTableName string) *shop {
	s.shopDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shop) As(alias string) *shop {
	s.shopDo.DO = *(s.shopDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shop) updateTableName(table string) *shop {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.Domain = field.NewString(table, "domain")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *shop) WithContext(ctx context.Context) IShopDo { return s.shopDo.WithContext(ctx) }

func (s shop) TableName() string { return s.shopDo.TableName() }

func (s shop) Alias() string { return s.shopDo.Alias() }

func (s shop) Columns(cols ...field.Expr) gen.Columns { return s.shopDo.Columns(cols...) }

func (s *shop) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shop) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["domain"] = s.Domain
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt

}

func (s shop) clone(db *gorm.DB) shop {
	s.shopDo.ReplaceConnPool(db.Statement.ConnPool)
	s.DeliveryRules.db = db.Session(&gorm.Session{Initialized: true})
	s.DeliveryRules.db.Statement.ConnPool = db.Statement.ConnPool
	s.AuditLogs.db = db.Session(&gorm.Session{Initialized: true})
	s.AuditLogs.db.Statement.ConnPool = db.Statement.ConnPool
	s.ConfigSnapshots.db = db.Session(&gorm.Session{Initialized: true})
	s.ConfigSnapshots.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s shop) replaceDB(db *gorm.DB) shop {
	s.shopDo.ReplaceDB(db)
	s.DeliveryRules.db = db.Session(&gorm.Session{})
	s.AuditLogs.db = db.Session(&gorm.Session{})
	s.ConfigSnapshots.db = db.Session(&gorm.Session{})
	return s
}

type shopHasManyDeliveryRules struct {
	db *gorm.DB

	field.RelationField

	Shop struct {
		field.RelationField
		DeliveryRules struct {
			field.RelationField
		}
		AuditLogs struct {
			field.RelationField
			Shop struct {
				field.RelationField
			}
			DeliveryRule struct {
				field.RelationField
			}
		}
		ConfigSnapshots struct {
			field.RelationField
			Shop struct {
				field.RelationField
			}
		}
	}
	AuditLogs struct {
		field.RelationField
	}
}

func (a shopHasManyDeliveryRules) Where(conds ...field.Expr) *shopHasManyDeliveryRules {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a shopHasManyDeliveryRules) WithContext(ctx context.Context) *shopHasManyDeliveryRules {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a shopHasManyDeliveryRules) Session(session *gorm.Session) *shopHasManyDeliveryRules {
	a.db = a.db.Session(session)
	return &a
}

func (a shopHasManyDeliveryRules) Model(m *model.Shop) *shopHasManyDeliveryRulesTx {
	return &shopHasManyDeliveryRulesTx{a.db.Model(m).Association(a.Name())}
}

func (a shopHasManyDeliveryRules) Unscoped() *shopHasManyDeliveryRules {
	a.db = a.db.Unscoped()
	return &a
}

type shopHasManyDeliveryRulesTx struct{ tx *gorm.Association }

func (a shopHasManyDeliveryRulesTx) Find() (result []*model.DeliveryRule, err error) {
	return result, a.tx.Find(&result)
}

func (a shopHasManyDeliveryRulesTx) Append(values ...*model.DeliveryRule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a shopHasManyDeliveryRulesTx) Replace(values ...*model.DeliveryRule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a shopHasManyDeliveryRulesTx) Delete(values ...*model.DeliveryRule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a shopHasManyDeliveryRulesTx) Clear() error {
	return a.tx.Clear()
}

func (a shopHasManyDeliveryRulesTx) Count() int64 {
	return a.tx.Count()
}

func (a shopHasManyDeliveryRulesTx) Unscoped() *shopHasManyDeliveryRulesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type shopHasManyAuditLogs struct {
	db *gorm.DB

	field.RelationField
}

func (a shopHasManyAuditLogs) Where(conds ...field.Expr) *shopHasManyAuditLogs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a shopHasManyAuditLogs) WithContext(ctx context.Context) *shopHasManyAuditLogs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a shopHasManyAuditLogs) Session(session *gorm.Session) *shopHasManyAuditLogs {
	a.db = a.db.Session(session)
	return &a
}

func (a shopHasManyAuditLogs) Model(m *model.Shop) *shopHasManyAuditLogsTx {
	return &shopHasManyAuditLogsTx{a.db.Model(m).Association(a.Name())}
}

func (a shopHasManyAuditLogs) Unscoped() *shopHasManyAuditLogs {
	a.db = a.db.Unscoped()
	return &a
}

type shopHasManyAuditLogsTx struct{ tx *gorm.Association }

func (a shopHasManyAuditLogsTx) Find() (result []*model.AuditLog, err error) {
	return result, a.tx.Find(&result)
}

func (a shopHasManyAuditLogsTx) Append(values ...*model.AuditLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a shopHasManyAuditLogsTx) Replace(values ...*model.AuditLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a shopHasManyAuditLogsTx) Delete(values ...*model.AuditLog) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a shopHasManyAuditLogsTx) Clear() error {
	return a.tx.Clear()
}

func (a shopHasManyAuditLogsTx) Count() int64 {
	return a.tx.Count()
}

func (a shopHasManyAuditLogsTx) Unscoped() *shopHasManyAuditLogsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type shopHasManyConfigSnapshots struct {
	db *gorm.DB

	field.RelationField
}

func (a shopHasManyConfigSnapshots) Where(conds ...field.Expr) *shopHasManyConfigSnapshots {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a shopHasManyConfigSnapshots) WithContext(ctx context.Context) *shopHasManyConfigSnapshots {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a shopHasManyConfigSnapshots) Session(session *gorm.Session) *shopHasManyConfigSnapshots {
	a.db = a.db.Session(session)
	return &a
}

func (a shopHasManyConfigSnapshots) Model(m *model.Shop) *shopHasManyConfigSnapshotsTx {
	return &shopHasManyConfigSnapshotsTx{a.db.Model(m).Association(a.Name())}
}

func (a shopHasManyConfigSnapshots) Unscoped() *shopHasManyConfigSnapshots {
	a.db = a.db.Unscoped()
	return &a
}

type shopHasManyConfigSnapshotsTx struct{ tx *gorm.Association }

func (a shopHasManyConfigSnapshotsTx) Find() (result []*model.FunctionConfigSnapshot, err error) {
	return result, a.tx.Find(&result)
}

func (a shopHasManyConfigSnapshotsTx) Append(values ...*model.FunctionConfigSnapshot) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a shopHasManyConfigSnapshotsTx) Replace(values ...*model.FunctionConfigSnapshot) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a shopHasManyConfigSnapshotsTx) Delete(values ...*model.FunctionConfigSnapshot) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a shopHasManyConfigSnapshotsTx) Clear() error {
	return a.tx.Clear()
}

func (a shopHasManyConfigSnapshotsTx) Count() int64 {
	return a.tx.Count()
}

func (a shopHasManyConfigSnapshotsTx) Unscoped() *shopHasManyConfigSnapshotsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type shopDo struct{ gen.DO }

type IShopDo interface {
	gen.SubQuery
	Debug() IShopDo
	WithContext(ctx context.Context) IShopDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IShopDo
	WriteDB() IShopDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IShopDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IShopDo
	Not(conds ...gen.Condition) IShopDo
	Or(conds ...gen.Condition) IShopDo
	Select(conds ...field.Expr) IShopDo
	Where(conds ...gen.Condition) IShopDo
	Order(conds ...field.Expr) IShopDo
	Distinct(cols ...field.Expr) IShopDo
	Omit(cols ...field.Expr) IShopDo
	Join(table schema.Tabler, on ...field.Expr) IShopDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IShopDo
	RightJoin(table schema.Tabler, on ...field.Expr) IShopDo
	Group(cols ...field.Expr) IShopDo
	Having(conds ...gen.Condition) IShopDo
	Limit(limit int) IShopDo
	Offset(offset int) IShopDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IShopDo
	Unscoped() IShopDo
	Create(values ...*model.Shop) error
	CreateInBatches(values []*model.Shop, batchSize int) error
	Save(values ...*model.Shop) error
	First() (*model.Shop, error)
	Take() (*model.Shop, error)
	Last() (*model.Shop, error)
	Find() ([]*model.Shop, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Shop, err error)
	FindInBatches(result *[]*model.Shop, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Shop) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IShopDo
	Assign(attrs ...field.AssignExpr) IShopDo
	Joins(fields ...field.RelationField) IShopDo
	Preload(fields ...field.RelationField) IShopDo
	FirstOrInit() (*model.Shop, error)
	FirstOrCreate() (*model.Shop, error)
	FindByPage(offset int, limit int) (result []*model.Shop, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IShopDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s shopDo) Debug() IShopDo {
	return s.withDO(s.DO.Debug())
}

func (s shopDo) WithContext(ctx context.Context) IShopDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shopDo) ReadDB() IShopDo {
	return s.Clauses(dbresolver.Read)
}

func (s shopDo) WriteDB() IShopDo {
	return s.Clauses(dbresolver.Write)
}

func (s shopDo) Session(config *gorm.Session) IShopDo {
	return s.withDO(s.DO.Session(config))
}

func (s shopDo) Clauses(conds ...clause.Expression) IShopDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shopDo) Returning(value interface{}, columns ...string) IShopDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shopDo) Not(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shopDo) Or(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shopDo) Select(conds ...field.Expr) IShopDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shopDo) Where(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shopDo) Order(conds ...field.Expr) IShopDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shopDo) Distinct(cols ...field.Expr) IShopDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shopDo) Omit(cols ...field.Expr) IShopDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shopDo) Join(table schema.Tabler, on ...field.Expr) IShopDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shopDo) LeftJoin(table schema.Tabler, on ...field.Expr) IShopDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shopDo) RightJoin(table schema.Tabler, on ...field.Expr) IShopDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shopDo) Group(cols ...field.Expr) IShopDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shopDo) Having(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shopDo) Limit(limit int) IShopDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shopDo) Offset(offset int) IShopDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shopDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IShopDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shopDo) Unscoped() IShopDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shopDo) Create(values ...*model.Shop) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shopDo) CreateInBatches(values []*model.Shop, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shopDo) Save(values ...*model.Shop) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shopDo) First() (*model.Shop, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shop), nil
	}
}

func (s shopDo) Take() (*model.Shop, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shop), nil
	}
}

func (s shopDo) Last() (*model.Shop, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shop), nil
	}
}

func (s shopDo) Find() ([]*model.Shop, error) {
	result, err := s.DO.Find()
	return result.([]*model.Shop), err
}

func (s shopDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Shop, err error) {
	buf := make([]*model.Shop, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shopDo) FindInBatches(result *[]*model.Shop, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shopDo) Attrs(attrs ...field.AssignExpr) IShopDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shopDo) Assign(attrs ...field.AssignExpr) IShopDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shopDo) Joins(fields ...field.RelationField) IShopDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shopDo) Preload(fields ...field.RelationField) IShopDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shopDo) FirstOrInit() (*model.Shop, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shop), nil
	}
}

func (s shopDo) FirstOrCreate() (*model.Shop, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shop), nil
	}
}

func (s shopDo) FindByPage(offset int, limit int) (result []*model.Shop, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shopDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shopDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shopDo) Delete(models ...*model.Shop) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shopDo) withDO(do gen.Dao) *shopDo {
	s.DO = *do.(*gen.DO)
	return s
}
